name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Test
        run: nix-shell --command 'make test'
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint
        run: nix-shell --command 'make lint'
      - name: Diff
        run: git diff
      - name: Status
        run: git status
      - name: Compare
        run: bash -c '[[ -z $(git status -s) ]] || (exit 1)'
